//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mapzip.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MapZip Installer")]
        public string ProductFriendlyName {
            get {
                return ((string)(this["ProductFriendlyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} (v{1}) by Jacob Jewett.")]
        public string Text_Welcome {
            get {
                return ((string)(this["Text_Welcome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reading configuration...")]
        public string Text_ReadingConfig {
            get {
                return ((string)(this["Text_ReadingConfig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Licenced under GNU General Public Licence v3.0")]
        public string Text_Licence {
            get {
                return ((string)(this["Text_Licence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config file empty or syntax malformed; Please report this to the mapmaker. Raw me" +
            "ssage: ")]
        public string Text_ErrConfigSyntax {
            get {
                return ((string)(this["Text_ErrConfigSyntax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config file layout mismatch. Local layout version 1, config verision {0}. Please " +
            "report this to the mapmaker.")]
        public string Text_ErrConfigVersionMismatch {
            get {
                return ((string)(this["Text_ErrConfigVersionMismatch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config file parsed with no errors.")]
        public string Text_ConfigReadSuccess {
            get {
                return ((string)(this["Text_ConfigReadSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Are you sure you want to install the map \"{0}\" by {1} (v{2})? (Y or N)")]
        public string Text_InstallConfirmation {
            get {
                return ((string)(this["Text_InstallConfirmation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!!! Save your game as it will be closed forcibly if not exited now. !!!")]
        public string Text_InstallNoticeGameSave {
            get {
                return ((string)(this["Text_InstallNoticeGameSave"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thanks for using {0} v{1}! Press any key to exit...")]
        public string Text_Thanks {
            get {
                return ((string)(this["Text_Thanks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MAPZIP,ERROR,CONFIG,INSTALLER,IO,AUTHENTICATION,CLI")]
        public string Text_Tags {
            get {
                return ((string)(this["Text_Tags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("------------------------------------------------------------")]
        public string Text_Separator {
            get {
                return ((string)(this["Text_Separator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The profile zip was not found. Please report this to the mapmaker.")]
        public string Text_ErrProfileMissing {
            get {
                return ((string)(this["Text_ErrProfileMissing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Argument parsing failed, errors returned. Raw message:")]
        public string Text_ErrArgumentErrors {
            get {
                return ((string)(this["Text_ErrArgumentErrors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This feature is not implemented yet.")]
        public string Text_NotImplemented {
            get {
                return ((string)(this["Text_NotImplemented"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage:@[--help]: Displays this help text.@[-c,--config]: Specify a custom config " +
            "file path.@[-d,--data]: Specify a custom profile data path.@[-s,--silent]: Bypas" +
            "s confirmation message.@[-u,--uninstall]: Uninstall the map this installer unpac" +
            "ks.")]
        public string Text_ArgumentsHelpText {
            get {
                return ((string)(this["Text_ArgumentsHelpText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The configuration file could not be located at {0}. Please report this to the map" +
            "maker.")]
        public string Text_ErrConfigMissing {
            get {
                return ((string)(this["Text_ErrConfigMissing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beggining install proccess. ")]
        public string Text_InstBegin {
            get {
                return ((string)(this["Text_InstBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verifying game directory...")]
        public string Text_InstVerifyGameDir {
            get {
                return ((string)(this["Text_InstVerifyGameDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Game directory missing. Please try running the Minecraft launcher once before usi" +
            "ng this installer.")]
        public string Text_InstGameDirMissing {
            get {
                return ((string)(this["Text_InstGameDirMissing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Exising installation of map found. Removing and reinstalling.")]
        public string Text_InstExistingFound {
            get {
                return ((string)(this["Text_InstExistingFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Existing manifest not found. Creating.")]
        public string Text_InstManifestMissing {
            get {
                return ((string)(this["Text_InstManifestMissing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Updating manifest with new map info.")]
        public string Text_InstUpdatingManifest {
            get {
                return ((string)(this["Text_InstUpdatingManifest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adding new profile to launcher.")]
        public string Text_InstUpdatingProfiles {
            get {
                return ((string)(this["Text_InstUpdatingProfiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Updating launcher profiles list.")]
        public string Text_InstCreatingProfile {
            get {
                return ((string)(this["Text_InstCreatingProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unzipping internal profile copy.")]
        public string Text_InstUnzippingProfile {
            get {
                return ((string)(this["Text_InstUnzippingProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Setting default user options from existing since once was not provided.")]
        public string Text_InstSettingDefaults {
            get {
                return ((string)(this["Text_InstSettingDefaults"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Installation completed.")]
        public string Text_InstCompleted {
            get {
                return ((string)(this["Text_InstCompleted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copying internal profile to new profile in game directory.")]
        public string Text_InstCopying {
            get {
                return ((string)(this["Text_InstCopying"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config file was empty. Please report this to the mapmaker.")]
        public string Text_ConfEmpty {
            get {
                return ((string)(this["Text_ConfEmpty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Could not find schema name \"{0}\" in dictionary. Please report this to the mapmake" +
            "r and developer.")]
        public string Text_ErrSchemaNameMissing {
            get {
                return ((string)(this["Text_ErrSchemaNameMissing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Launcher profiles structure version mismatch. Please report this to the mapmaker " +
            "and developer.")]
        public string Text_ErrLauncherLayoutMismatch {
            get {
                return ((string)(this["Text_ErrLauncherLayoutMismatch"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Found game directory.")]
        public string Text_InstGameDirFound {
            get {
                return ((string)(this["Text_InstGameDirFound"]));
            }
            set {
                this["Text_InstGameDirFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The installer aborted operation unexpectedly. Please report this to the mapmaker " +
            "including the installer version ({0}), the installer log file or console output," +
            " the map you are attempting to install ({1}) and your basic system info.")]
        public string Text_InstAborted {
            get {
                return ((string)(this["Text_InstAborted"]));
            }
            set {
                this["Text_InstAborted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Launcher configuration file was not found. Please attempt to launch the Minecraft" +
            " launcher first/again before running this installer.")]
        public string Text_LauncherFileMissing {
            get {
                return ((string)(this["Text_LauncherFileMissing"]));
            }
            set {
                this["Text_LauncherFileMissing"] = value;
            }
        }
    }
}
